project:
  type: website
  output-dir: docs

website:
  title: "Datamining2025"
  navbar:
    left:
      - href: index.qmd
        text: "A propos"
      - text: "API"
        menu:
          - href: 10-API-Theorie.qmd
            text: "Théorie"
          - href: 11-API-Import-json.qmd
            text: "Importation json"
          - href: 12-API-Import-geojson.qmd
            text: "Importation geojson"
          - href: 13-API-Exercices.qmd
            text: "Exercices"
      - text: "Cartographie"
        menu:
          - href: 21-CARTO-ParisPC.qmd
            text: "Préparation avec sf"
          - href: 22-CARTO-mapsf.qmd
            text: "Cartographie statique"    
          - href: 23-CARTO-leaflet.qmd
            text: "Cartographie dynamique" 
      - text: "Projet JOCAS"
        menu:
          - href: 31-JOCAS-preparation.qmd
            text: "Préparation"
          - href: 32-JOCAS-agregation.qmd
            text: "Agregation"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/datamining2025
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


