project:
  type: website
  output-dir: docs

website:
  title: "Datamining2025"
  navbar:
    left:
      - href: index.qmd
        text: "A propos"
      - text: "API"
        menu:
          - href: 10-API-Theorie.qmd
            text: "Théorie"
          - href: 11-API-Import-json.qmd
            text: "Importation json"
          - href: 12-API-Import-geojson.qmd
            text: "Importation geojson"
          - href: 13-API-Exercices.qmd
            text: "Exercices"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/theoregio
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


